import { writeFile } from "fs/promises";
import type { CrossCtxOutput } from "../types/index.js";

/**
 * Generate LLM-optimized Markdown summary
 * Designed to be pasted directly into an LLM prompt
 */
export function renderMarkdown(output: CrossCtxOutput): string {
  const lines: string[] = [];

  lines.push("# API Dependency Map");
  lines.push("");
  lines.push(`> Generated by CrossCtx v${output.meta.version} on ${output.meta.generatedAt}`);
  lines.push("");

  // Services overview
  lines.push("## Services");
  lines.push("");
  for (const svc of output.services) {
    lines.push(`### ${svc.name}`);
    lines.push("");
    if (svc.baseUrls.length > 0) {
      lines.push(`- **Base URL:** ${svc.baseUrls.join(", ")}`);
    }
    lines.push(`- **Spec version:** ${svc.specVersion}`);
    lines.push(`- **Endpoints:** ${svc.endpointCount}`);
    lines.push("");
  }

  // Endpoints table
  lines.push("## Endpoints");
  lines.push("");
  lines.push("| Service | Method | Path | Summary |");
  lines.push("|---------|--------|------|---------|");
  for (const ep of output.endpoints) {
    const summary = ep.summary || "-";
    lines.push(`| ${ep.service} | ${ep.method} | \`${ep.path}\` | ${summary} |`);
  }
  lines.push("");

  // Dependencies
  if (output.dependencies.length > 0) {
    lines.push("## Dependencies");
    lines.push("");
    lines.push("```");
    for (const dep of output.dependencies) {
      lines.push(`${dep.from} → ${dep.to}  (${dep.detectedVia})`);
    }
    lines.push("```");
    lines.push("");

    // Dependency detail
    lines.push("### Dependency Details");
    lines.push("");
    for (const dep of output.dependencies) {
      lines.push(`- **${dep.from}** → **${dep.to}**`);
      lines.push(`  - Detected via: ${dep.detectedVia}`);
      lines.push(`  - Evidence: ${dep.evidence}`);
    }
    lines.push("");
  } else {
    lines.push("## Dependencies");
    lines.push("");
    lines.push("No inter-service dependencies detected.");
    lines.push("");
  }

  // Schema summary (compact for LLM consumption)
  const endpointsWithSchemas = output.endpoints.filter((e) => e.requestBody || e.response);
  if (endpointsWithSchemas.length > 0) {
    lines.push("## Schemas (Simplified)");
    lines.push("");
    for (const ep of endpointsWithSchemas) {
      lines.push(`**${ep.method} ${ep.path}** (${ep.service})`);
      if (ep.requestBody) {
        const props = ep.requestBody.properties
          ? Object.entries(ep.requestBody.properties)
              .map(([k, v]) => `${k}: ${v}`)
              .join(", ")
          : ep.requestBody.type;
        lines.push(`- Request: { ${props} }`);
      }
      if (ep.response) {
        const props = ep.response.properties
          ? Object.entries(ep.response.properties)
              .map(([k, v]) => `${k}: ${v}`)
              .join(", ")
          : ep.response.type;
        lines.push(`- Response: ${ep.response.type === "array" ? `[{ ${props} }]` : `{ ${props} }`}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Save Markdown output to file
 */
export async function saveMarkdown(output: CrossCtxOutput, outputPath: string): Promise<void> {
  const md = renderMarkdown(output);
  await writeFile(outputPath, md, "utf-8");
}
